import requests
import json
import os
import sys

def test_document_generation():
    # Sample HTML content
    content_html = """
    <h1 style="color: #333; text-align: center;">Sample Document</h1>
    <p style="margin: 15px 0;">This is a test document generated by our Document Generation Service.</p>
    <ul>
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3 with <strong>bold text</strong></li>
    </ul>
    <p>Below is a sample table:</p>
    <table border="1" cellpadding="5" style="width: 100%; border-collapse: collapse;">
        <tr style="background-color: #f2f2f2;">
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
        </tr>
        <tr>
            <td>John Doe</td>
            <td>john@example.com</td>
            <td>Developer</td>
        </tr>
        <tr>
            <td>Jane Smith</td>
            <td>jane@example.com</td>
            <td>Designer</td>
        </tr>
    </table>
    """

    header_html = """
    <div style="text-align: center; font-size: 10px; color: #777;">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAB2AAAAdgB+lymcgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAPiSURBVHic7ZpNSFRRFMd/M42laZM2RURQIRZFUbSJIopA3LQKF0VEi6CFi6JVQUTQLiKIqE0WQXSIKI0QaiNYC7VdSFFJRlAUKFQ0Ey0cZ6a3mNtjnrzvvpf4ob95i3vPeffcc+be+/733FGSKHdUlPsBFopi7IB14E/gK/AJ+Ai8A6aAb8A34WdJKsFzgA3ABaADaLbH74FuYBAYB34Dr4E3wEuiBfAA6AM+A/+AV7YtEfKZAdXADmA9sMXOPgL9wJCOzbo7YD9wB5gDJoELQLOh2PWBcW8EtgGrURqnvTUJMMmdXr0EmuK6LpQDdOuNbsPlWTXr2p1Cfz6s2R7XOEyb3bp16ohI75VkzeY4hgdJuiO2X7LchrUuyTGE37OJWm6-TCTpclDDO5KcLYHxPiRpNEz3XJCmbkm3SmicD0m6EqS9OUjTYJL2iTvAj4mOVS4G8pZoF6hA2QFu5H0sipQd4EbeIgsiqQ5IpJe4dYYXgWPAOLATPUXeBl4Az4gW5U3AXvTU+QltI9W2XQPqgFagDtgKnLTPDnvFIVOsFPgMaxXQ5dBnLXrr7Ei4AuXG55QDTqPVpSDdKWAtcDii8XYcBw+hk6j9wC570AlgBO3sMeBnBLvWAEeBBvTssw9t8Czai+FI4nLNgGZ0IADj6FXXsIf+FrryS0I/MIqeXT4Ap+xxU/vbCp0BF9EuBLiJu/EAw8CkR92k1TVut8c9hnMO0AkB+BSiOw7M+Jw7Cy7YdtrjNC7nABPzT6M35UFs9Ti32sOWKN9zo/m2+tCPc4DpfMzD+EI5gZ7uHgJHgPPAHXtOCMKYytZ5nB/nALMyrfLQeRw6Xco5q2vG8AA96xQDJ9Brij/Ac2APITsyEmIR0IXeiz8F7qJX4+sjtKtDe340ggPWoN0FOIHeQF8ORixrkfmELtV+hrHXNNOZCO0K3VZOoWR/7uQniOvAIXQC1EiZtF8L6yAfB9Rby70MnT2FCMx89bnSLGnQ1hS7bPGTaTKkyiRJA16KkYixXZG0WLvAmN1nR2hVmVtHtaTrtj1TGVoCOZEk2G4bDhkxBL8wpM45R1vtKVAzsakgzzsrJJ2zL/DU0a5Y+wBJajV5wVgCII6k8/bXW+Boc6QZkNtnuJ2zXdXyTHC2CAX8UEO+8+1HdI5fh16ifojYfgQ9DZ4gyxZ3O3uHrGTpHLpqPIfOFBfUeNvsVfRm6CLeUh3QeYBnd1IUbCdzeXQVv2QoDrdJGpeUKeDFfpC0L659JcOS26d3i94Vi2OTeVm5URnkAeWO/FPh5USi7iUR00uUB5Q78i+FywnlAWWfB/wH9aqhGKMCVrkAAAAASUVORK5CYII=" height="20" />
        <span>Document Generation Service - Header</span>
    </div>
    """
    
    footer_html = """
    <div style="text-align: center; font-size: 10px; color: #777;">
        <hr style="margin: 5px 0;" />
        <p>Page <span class="pageNumber"></span> of <span class="totalPages"></span> - Generated on March 25, 2023</p>
    </div>
    """
    
    watermark = """
    <div style="transform: rotate(-45deg); font-size: 60px; color: rgba(200, 200, 200, 0.3); text-align: center;">
        CONFIDENTIAL
    </div>
    """
    
    # Create directory for output files if it doesn't exist
    os.makedirs("demo/output", exist_ok=True)
    
    # Test PDF generation
    print("Testing PDF generation...")
    pdf_data = {
        "content_html": content_html,
        "header_html": header_html,
        "footer_html": footer_html,
        "document_type": "pdf",
        "watermark": watermark
    }
    
    pdf_response = requests.post(
        "http://localhost:5000/api/v1/generate",
        json=pdf_data,
        headers={"Content-Type": "application/json"}
    )
    
    if pdf_response.status_code == 200:
        with open("demo/output/sample.pdf", "wb") as f:
            f.write(pdf_response.content)
        print("PDF generated successfully! Saved to demo/output/sample.pdf")
    else:
        print(f"PDF generation failed with status code {pdf_response.status_code}")
        print(pdf_response.text)
    
    # Test DOCX generation
    print("Testing DOCX generation...")
    docx_data = {
        "content_html": content_html,
        "header_html": header_html,
        "footer_html": footer_html,
        "document_type": "docx",
        "watermark": watermark
    }
    
    docx_response = requests.post(
        "http://localhost:5000/api/v1/generate",
        json=docx_data,
        headers={"Content-Type": "application/json"}
    )
    
    if docx_response.status_code == 200:
        with open("demo/output/sample.docx", "wb") as f:
            f.write(docx_response.content)
        print("DOCX generated successfully! Saved to demo/output/sample.docx")
    else:
        print(f"DOCX generation failed with status code {docx_response.status_code}")
        print(docx_response.text)

if __name__ == "__main__":
    test_document_generation()